name: Hello World # Workflow name . As we already know we create a repo -> then in the repo we create -> workflow a
                  # And in that workflow we create the jobs and jobs are nothing but let say if we are implementing ci 
                  # so jobs are build and test .concurrency: 
on: push # this is triggers configured as on concurrency: 
jobs:
  build:              # this is the job name which u created inside your workflow 
    runs-on: ubuntu-latest
    steps:            #Step is what we want to perform in a job . steps are the individual actions or commands that run inside a job, one after another.
                      # runs-on → machine (Ubuntu / Windows / macOs)
                      # steps → commands like checkout, build, test, deploy
      - name: Build Phase  
        run: echo "Hello, ${{vars.My_Name}}" # Created a variable after this i will create a secret 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Phase
        run: echo "The Test has been Successfully conducted"
          

  # we can create and run multiple shell commands in a single step above example is the evidence of this
